---
#Allgemeine Einstellungen
ConfigVersion: 6.1.1 #FingerWeg! Dont touch this!

#Commands & Funktionen
BoosterCommand: false #Muss Überarbeitet werden jedoch aktuell keine Zeit dafür...
StarterKit: true #Aktiviere\Deaktiviere das StarterKit
Kits: false #Aktiviere\Deaktiviere das KitSystem Braucht eine überarbeitung
VoteSystem: true #Aktiviere\Deaktiviere das VoteSystem
Buchstabenraetsel: false
#In Modules.yml sind die restlichen funktionen die man ändern kann!

#ItemDisplay
inames: true #aktiviere/deaktiviere die ItemNamen

#Join/QuitMessages:
#Stelle hier die JoinMessage ein / {prefix} {player} {count} {slots}
JoinMessage: true
Joinmsg: "§f[§a+§f] {prefix} {player} §ahat den Server betreten! §f[§a{count}§f/§a{slots}§f]"
#Stelle hier die Quitmessage ein / {prefix} {player} {count} {slots}
QuitMessage: true
Quitmsg: "§f[§c-§f] {prefix} {player} §chat den Server verlassen! §f[§a{count}§f/§a{slots}§f]"
#Stelle hier den JoinTip ein / {player}
JoinTip: true
Tipmsg: "§eDanke das du die CoreV6 benutzt {player}"
#Stelle hier den JoinTitle ein / {player}
JoinTitle: true
Titlemsg: "§dWillkommen"
Subtitlemsg: "§e{player}"
#Blitze beim Join
blitze: true #aktiviere/deaktiviere Blitze beim Joinen des Servers
totem: true #aktiviere/deaktivere den TotenEffect
sound: true #aktiviere/deaktiviere den Donner

#Rejoin
#Stelle hier ein ob du willst das die Spieler automatich mit dem Server nach einem Neustart verbunden werden
Rejoin: false
IP: noteland.citybuild.one
Port: 19132

#NetzwerkName
networkname: "§f[§eCore§4V6§f] §eBETA" #schreibe hier dein servername oder was frag mich rein...

#CoinSystem
DefaultCoins: 100
#EconomySystem
DefaultMoney: 1000

#Weitere Einstellungen
defaultspawn: true
maxhomes: 10 #Setze ein Limit für Homes
collision: true #aktiviere/deaktiviere collision/schubsen
keepinventory: true #setze auf true um dein Inventar zu Behalten
PingLimit: 30000 #Setze das Maximale Pinglimit ein
ExplodeEgg: true #Setzt auf True um Explodierende Eier ohne Damage zu erhalten!

#Regelwerk
Regeln: false #Entscheide selber ob du die Regeln nutzten willst oder nicht...

#FFA
FFA: false #Aktiviere/Deaktiviere FFA
FFA_Map: FFA #Setze hier deine Welt ein wo du FFA Nutzen willst

#HubCommand
Defaultworld: world #Setze hier die Defaultwelt
Gamemode: 2 #setze hier den Gamemode für die Welt
Food: true #Aktivier/Deaktivier das Auffüllen des Hungers
Heal: true #Aktivier/Deaktivier das Auffüllen des Lebens
Teleportsound: true #Aktivier/Deaktivier den Teleportsound
##Einstellungen für das Voten

#Voten Aktivieren/Deaktivieren
votes: false # aktiviere oder deaktiviere den /vote command
#Wo bekomme ich die minecraftpocket-servers-com.vrc file her?
#Step:1 Gehe auf https://minecraftpocket-servers.com
#Step:2 Gehe auf My Options dann auf "Manage Yours Servers"
#Step:3 Nun siehste deine Server! Drücke neben "VRC File" auf das Downloadsymbol
#Step:4 Nun fügste die datai.vrc  in plugin_data/CoreV5/Setup ein
#Nun ist alles erledigt und du solltest das VoteSystem nun nutzen können!
VoteLink: "https://bit.ly/NLvote"
#Aktiviere/Deaktiviere den MindestVote
MussVoten: false #nutze true/false zum Aktivieren oder Deaktivieren. Standart ist false
Mindestvotes: 1 #ändere die anzahl der Votes die man Benötigt um in den Chat zu schreiben oder eine MSG zu schreiben etc

#LiftSystem
helferprivatliftuse: true
helperprivateLift: true
checkFloor: true

#Leaderboard
leaderboard: false
X: 0
Y: 0
Z: 0
level: world

#Sperre hier die Events in den Welten!
Place:
  - world
  - Lobby
Break:
  - world
  - Lobby
Chat:
  - world
  - Lobby
Drop:
  - world
  - Lobby
Bucketempty:
  - world
  - Lobby
Bucketfill:
  - world
  - Lobby

#RankShop
RankShopCommand: false #<- Setze es auf false um dem Command zu deaktivieren!

Rankname1: premium #<- Setze hier die Gruppe rein (Muss genauso heißen wie die Gruppe!
Rankprice1: 125000 #<- Setze hier den Betrag fest!
#Hier kannst du 6 Weitere Ränge einstellen!
Rank2: false
Rankname2: normal
Rankprice2: 0

Rank3: false
Rankname3: normal
Rankprice3: 0

Rank4: false
Rankname4: normal
Rankprice4: 0

Rank5: false
Rankname5: normal
Rankprice5: 0

Rank6: false
Rankname6: normal
Rankprice6: 0

Rank7: false
Rankname7: normal
Rankprice7: 0


##PowerBlock Einstellungen

PowerBlock: true #Aktiviere\Deaktiviere den PowerBlock

##PowerBlock 1
BlockID1: 100 #Setze hier die Blockid hin
BlockStaerke1: 5 #Setze hier die Stärke ein
BlockSound1: AnvilFallSound

##PowerBlock 2
BlockID2: 133
BlockStaerke2: 4
BlockSound: GhastShootSound

##Verfügbare Sounds
#AnvilFallSound, ClickSound, EndermanTeleportSound, GhastShootSound, PopSound
...